// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjH6rm6B03iJdf5uOj-v_nBfhTdFrgO4',
    appId: '1:576502046454:web:eb4bbb346ab30661a216d7',
    messagingSenderId: '576502046454',
    projectId: 'jokeis-chat',
    authDomain: 'jokeis-chat.firebaseapp.com',
    storageBucket: 'jokeis-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5x7gq6KyalSh44nYUIt60X78HhwAHEs',
    appId: '1:576502046454:android:4d96b79bf1a09666a216d7',
    messagingSenderId: '576502046454',
    projectId: 'jokeis-chat',
    storageBucket: 'jokeis-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rWy9wTEvNFAFMFskk81HWch-d3ULnbM',
    appId: '1:576502046454:ios:ff872d518152f5dca216d7',
    messagingSenderId: '576502046454',
    projectId: 'jokeis-chat',
    storageBucket: 'jokeis-chat.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rWy9wTEvNFAFMFskk81HWch-d3ULnbM',
    appId: '1:576502046454:ios:009b5e82ab64ad9da216d7',
    messagingSenderId: '576502046454',
    projectId: 'jokeis-chat',
    storageBucket: 'jokeis-chat.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
